// This file is generated by kysely-codegen. Do not modify manually.
// Generated from supabase schema on Fri Apr 03 2026

export interface DB {
  address_book: {
    id: string;
    owner_id: string;
    contact_id: string;
    first_handshake_id: string | null;
    created_at: Date;
  };
  ads: {
    id: string;
    dealer_id: string;
    campaign_name: string | null;
    start_date: string | null;
    end_date: string | null;
    budget_total: number | null;
    budget_remaining: number | null;
    impressions: number;
    clicks: number;
    ctr: number;
    cpc: number;
    status: string;
    moderation_status: string;
    rejection_reason: string | null;
    created_at: Date;
    updated_at: Date;
  };
  async_jobs: {
    id: string;
    job_type: string;
    status: string;
    payload: Json;
    result: Json | null;
    attempts: number;
    max_attempts: number;
    last_error: string | null;
    scheduled_at: Date | null;
    created_at: Date;
    updated_at: Date;
  };
  audit_purge_queue: {
    id: string;
    profile_id: string;
    reason: string;
    requested_by: string | null;
    approved_by: string | null;
    status: string;
    created_at: Date;
    completed_at: Date | null;
  };
  connections: {
    id: string;
    requester_id: string;
    target_id: string;
    status: string;
    created_at: Date;
    updated_at: Date;
  };
  equipment: {
    id: string;
    dealer_id: string;
    name: string;
    description: string | null;
    daily_rate: number | null;
    weekly_rate: number | null;
    monthly_rate: number | null;
    location: string;
    available: boolean;
    images: string[];
    features: string[];
    created_at: Date;
    updated_at: Date;
  };
  invoices: {
    id: string;
    profile_id: string;
    invoice_number: string;
    amount: number;
    status: string;
    due_date: Date;
    paid_date: Date | null;
    created_at: Date;
    updated_at: Date;
  };
  portfolio_items: {
    id: string;
    profile_id: string;
    title: string;
    description: string | null;
    image_url: string;
    category: string;
    tags: string[];
    created_at: Date;
    updated_at: Date;
  };
  products: {
    id: string;
    seller_id: string;
    name: string;
    description: string | null;
    category: string;
    subcategory: string | null;
    price_per_unit: number;
    unit: string;
    min_order_quantity: number;
    images: string[];
    specifications: Json;
    available: boolean;
    created_at: Date;
    updated_at: Date;
  };
  profiles: {
    id: string;
    email: string;
    full_name: string | null;
    avatar_url: string | null;
    phone_number: string | null;
    address: string | null;
    city: string | null;
    state: string | null;
    postal_code: string | null;
    country: string | null;
    gstin: string | null;
    role: string;
    created_at: Date;
    updated_at: Date;
  };
  project_milestones: {
    id: string;
    project_id: string;
    title: string;
    description: string | null;
    due_date: Date | null;
    status: string;
    created_at: Date;
    updated_at: Date;
  };
  projects: {
    id: string;
    owner_id: string;
    title: string;
    description: string | null;
    status: string;
    created_at: Date;
    updated_at: Date;
  };
  rfps: {
    id: string;
    requester_id: string;
    title: string;
    description: string | null;
    category: string;
    subcategory: string | null;
    budget_min: number | null;
    budget_max: number | null;
    location: string | null;
    expiry_date: Date;
    status: string;
    created_at: Date;
    updated_at: Date;
  };
  roles: {
    id: string;
    profile_id: string;
    role_name: string;
    permissions: Json;
    created_at: Date;
    updated_at: Date;
  };
  system_audit_log: {
    id: string;
    actor_id: string | null;
    action: string;
    target_type: string | null;
    target_id: string | null;
    old_value: Json | null;
    new_value: Json | null;
    ip_address: string | null;
    user_agent: string | null;
    created_at: Date;
  };
  system_config: {
    key: string;
    value: Json;
    description: string | null;
    updated_at: Date;
  };
  unmasking_audit: {
    id: string;
    viewer_id: string;
    viewed_id: string;
    unmasked_at: Date;
    retention_expires_at: Date;
    created_at: Date;
  };
}

// Helper type for JSONB columns
interface Json {
  [key: string]: any;
}