// =============================================================================
// Shared Constants — Single source of truth for all magic strings
// =============================================================================

// Subscription
export const SUBSCRIPTION_STATUS = {
  TRIAL: 'trial',
  ACTIVE: 'active',
  EXPIRED: 'expired',
  HARD_LOCKED: 'hard_locked',
} as const;

export const MONTHLY_CREDITS = 30;
export const TRIAL_DURATION_HOURS = 48;
export const TRIAL_LOCK_THRESHOLD_HOURS = 49;

// Connection
export const CONNECTION_STATUS = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  BLOCKED: 'BLOCKED',
} as const;

// Persona Types
export const PERSONA_TYPES = {
  PP: 'PP',
  C: 'C',
  CON: 'CON',
  PS: 'PS',
  ED: 'ED',
} as const;

// RFP
export const RFP_STATUS = {
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export const RFP_TITLE_MIN_LENGTH = 10;
export const RFP_TITLE_MAX_LENGTH = 100;
export const RFP_DESCRIPTION_MIN_LENGTH = 50;
export const RFP_DESCRIPTION_MAX_LENGTH = 2000;

// RFP Response
export const RFP_RESPONSE_STATUS = {
  SUBMITTED: 'SUBMITTED',
  SHORTLISTED: 'SHORTLISTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;

// Ads
export const AD_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_MODERATION: 'PENDING_MODERATION',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED',
} as const;

// Moderation
export const MODERATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED',
  SUSPENDED: 'SUSPENDED',
  CLEARED: 'CLEARED',
} as const;

// Verification
export const VERIFICATION_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  PENDING_ADMIN: 'PENDING_ADMIN',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

// Notification Types
export const NOTIFICATION_TYPES = {
  CONNECTION_REQUESTED: 'CONNECTION_REQUESTED',
  CONNECTION_ACCEPTED: 'CONNECTION_ACCEPTED',
  CONNECTION_REJECTED: 'CONNECTION_REJECTED',
  CONNECTION_EXPIRED: 'CONNECTION_EXPIRED',
  RFP_CREATED: 'RFP_CREATED',
  RFP_RESPONSE_SUBMITTED: 'RFP_RESPONSE_SUBMITTED',
  RFP_RESPONSE_ACCEPTED: 'RFP_RESPONSE_ACCEPTED',
  RFP_EXPIRED: 'RFP_EXPIRED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PROFILE_VERIFICATION: 'PROFILE_VERIFICATION',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
  AD_APPROVED: 'AD_APPROVED',
  AD_REJECTED: 'AD_REJECTED',
  AD_EXPIRED: 'AD_EXPIRED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATIONS_READ_ALL: 'NOTIFICATIONS_READ_ALL',
} as const;

// DQS
export const DQS_WEIGHTS = {
  QUALITY: 0.7,
  DISTANCE: 0.3,
} as const;

export const DQS_FORMULA_WEIGHTS = {
  RESPONSIVENESS: 0.4,
  TRUST_LOOPS: 0.3,
  VERIFICATION: 0.2,
  PROFILE_DEPTH: 0.1,
} as const;

// Pagination
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 50;

// Regex patterns (source of truth — DB constraints must match)
export const GSTIN_REGEX = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
export const PAN_REGEX = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;

// PhonePe
export const PHONEPE_UAT_URL = 'https://api-preprod.phonepe.com/apis/pg-sandbox';
export const PHONEPE_PROD_URL = 'https://api.phonepe.com/apis/hermes';

// Error Codes
export const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RFP_TITLE_LENGTH_INVALID: 'RFP_TITLE_LENGTH_INVALID',
  RFP_DESCRIPTION_LENGTH_INVALID: 'RFP_DESCRIPTION_LENGTH_INVALID',
  RFP_DESCRIPTION_REQUIRED: 'RFP_DESCRIPTION_REQUIRED',
  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  // Handshake
  HANDSHAKE_INITIATE_SELF_CONNECT: 'HANDSHAKE_INITIATE_SELF_CONNECT',
  HANDSHAKE_INSUFFICIENT_CREDITS: 'HANDSHAKE_INSUFFICIENT_CREDITS',
  HANDSHAKE_SUBSCRIPTION_LOCKED: 'HANDSHAKE_SUBSCRIPTION_LOCKED',
  // Subscription
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_DOWNGRADE_NOT_ACTIVE: 'SUBSCRIPTION_DOWNGRADE_NOT_ACTIVE',
  // Product
  PRODUCT_CREATE_NOT_PS: 'PRODUCT_CREATE_NOT_PS',
  PRODUCT_CREATE_SUBSCRIPTION_LOCKED: 'PRODUCT_CREATE_SUBSCRIPTION_LOCKED',
  // Equipment
  EQUIPMENT_CREATE_NOT_ED: 'EQUIPMENT_CREATE_NOT_ED',
  EQUIPMENT_CREATE_SUBSCRIPTION_LOCKED: 'EQUIPMENT_CREATE_SUBSCRIPTION_LOCKED',
  // Ads
  ADS_CREATE_SUBSCRIPTION_LOCKED: 'ADS_CREATE_SUBSCRIPTION_LOCKED',
  ADS_UPDATE_NOT_DRAFT: 'ADS_UPDATE_NOT_DRAFT',
} as const;
